### ISSUE TITLE
2022-04-30T23:05:00.810 [ERROR] Failed to load module "rest_api": [Errno 98] Address already in use

### ISSUE THREAD

**Issue by ghost** [jesopo/bitbot#345]
Hi guys,

got this error: 2022-04-30T23:05:00.810 [ERROR] Failed to load module "rest_api": [Errno 98] Address already in use, when i launch rest_api. I even try changing the ports on rest_api.py.

Can´t get with the problem.

**Comment by examknow** [comment]
The port you're trying to use is likely already in use
